### ISSUE TITLE
User Statistics

### ISSUE THREAD

**Issue by andyl** [bugmark/test_bench#120]
Write a script that generates user statistics for InfluxDB.

We'd like to generate graphs showing activity per user:
- [x] balance
- [x] reserve
- [x] open offers
- [x] closed offers
- [x] contracts

We need three things:
- [x] A script that generates metrics and writes them to influxDB
- [x] A cron process that auto-runs the script every 20 minutes
- [x] Grafana Graphs that show the metrics

**Comment by snehasi** [comment]
https://github.com/bugmark/test_bench/pull/129
