### ISSUE TITLE
Remove 'Resolution' from 'open offer tab' in issue detail page OR add contract tab

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/test_bench#123]
The offer disappears when it is accepted and a contract is formed, as such, we do not need the 'resolution' column.

Alternatively, add a tab for 'contracts' on that issue and keep the table the same.

![image](https://user-images.githubusercontent.com/8862021/43082913-d54d83cc-8e5a-11e8-8a95-6359b78ff2e4.png)

**Comment by andyl** [comment]
Done.  Removed the resolution column, and added a `Contracts` tab.
