### ISSUE TITLE
Remember the consent endorsement

### ISSUE THREAD

**Issue by bugmarkdev** [bugmark/test_bench#2]
Currently you have to re-click the UNO consent form after every login.

Enhancement: remember the first time the UNO consent form is accepted, record the username and datetime.  Make sure that the recording solution complies with privacy guidelines.

**Comment by andyl** [comment]
Done.  Consent time is saved in the the trial repo `.trial_data/Access.yml`. Hash key is the encrypted user email.  String class extended with `lcl_encrypt` and `lcl_decrypt` methods.
