### ISSUE TITLE
Record Training Session

### ISSUE THREAD

**Issue by andyl** [bugmark/test_bench#20]
Publish a screencast with a video training session for the exercises.

- [x] write a screencasting script
- [x] find Ubuntu-compatible authoring software
- [x] figure out a publishing method

**Comment by andyl** [comment]
On Ubuntu: using "kazam" screencasting software.

**Comment by GeorgLink** [comment]
I recorded today's session and after cutting the beginning and end, I think it will serve our purpose just fine.

We created the screencasting script this morning and will be publishing it on YouTube.

**Comment by andyl** [comment]
Agreed - today's video session was great.  Thanks for doing the screen-editing.
