### ISSUE TITLE
Unique password for each participant

### ISSUE THREAD

**Issue by malvikarao** [bugmark/test_bench#24]
We need to generate unique passwords for each participant. These will be sent out with the zoom training session details in separate emails.

**Comment by andyl** [comment]
@GeorgLink @malvikarao this is now working.  The password-generation algorithm works like this.
1. start with your email eg `andy@r210.com`
2. split at the `@` character and save the first part as `usr_name`
3. the password is `bugmark-<usr_name>` in this case the password is `bugmark-andy`
