### ISSUE TITLE
Start/end dates must have start/end times as well

### ISSUE THREAD

**Issue by malvikarao** [bugmark/test_bench#25]
The times could be set to May 14th 12am PT start and May 17th 12pm PT end for example.

After the end date participants should no longer be able to change any data (so we shut down the website link, for instance).

Participants can access the website and login prior to the start date. This enables them to familiarize themselves with the website. However we do not want them to trade on the experiment issues in bugmark_docs. A solution might be to hook the platform to another issue tracker (e.g., bugmark/exchange) and switch issue trackers on May 14th. All data generated prior to May 14th must also be reset.

**Comment by andyl** [comment]
I'm going to stick with dates as is - it seems to be working OK.  Transition time is always Midnight in the server locale.
