### ISSUE TITLE
Crossed issues should be indicated as "crossed" in list views

### ISSUE THREAD

**Issue by richbodo** [bugmark/test_bench#52]
I can't tell what issues to grab.

I'm finding that the unresolved issues in the list view are crossed.  

I can't just look at this list to find an uncrossed issue.

See image below - as of this time, many of the unresolved issues are crossed:

<img width="1404" alt="screen shot 2018-05-17 at 1 05 05 pm" src="https://user-images.githubusercontent.com/93385/40201544-367e85b2-59d4-11e8-95ab-17daca44ad6c.png">

**Comment by andyl** [comment]
Issue page now shows open offers and contracts.
