### ISSUE TITLE
Refactor Issue Page

### ISSUE THREAD

**Issue by andyl** [bugmark/test_bench#84]
## New Design for Issue Page

![image](https://user-images.githubusercontent.com/90030/41193299-17979a42-6bbf-11e8-8874-a2ece408385e.png)
1) Jquery Multi-select checkbox 
  - can only multiselect offers w/same maturation 
  - displays accept/cancel button
2) Button that brings up "New Offer" modal
3) Tooltip that shows expiration date - color coded blue/yellow
4) Cancel button only shows for your open offers

## New Design for Create Offer Modal

![image](https://user-images.githubusercontent.com/90030/41193294-f89f8cd0-6bbe-11e8-83bb-32b97731295e.png)
TODO:
- design the expiration widget

**Comment by andyl** [comment]
Here's a screenshot of the Modal...
![image](https://user-images.githubusercontent.com/90030/41421516-d6455f0c-6fab-11e8-9cba-6295f64a1d4b.png)

**Comment by GeorgLink** [comment]
Modal looks good

**Comment by andyl** [comment]
Side-by-side view of two different user sessions...
![image](https://user-images.githubusercontent.com/90030/41424045-cc666570-6fb1-11e8-9afc-b4d4bf830077.png)

**Comment by andyl** [comment]
Done.
