### ISSUE TITLE
Trader Exercise: Calculation of earnings unclear

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/test_bench#97]
A user who has three positions and tried but failed to resell them sees on the account page an earning of 100 tokens, when the three positions awarded should add up to 60 only. Where do the remaining 40 come from? 

E.g. issue 1241

**Comment by andyl** [comment]
Now the account page has a balance breakdown, showing deposits/withdrawals, escrow collection and distribution.  Going to mark this closed, and we can re-open if the account balance shows problems.
