### ISSUE TITLE
Intern Exercise : specific error on issue 625 of outreachy repo

### ISSUE THREAD

**Issue by snehasi** [bugmark/test_bench#98]
I got the following error on issue 625 of outreachy repo, although it exists in the repo and is open:

![error](https://user-images.githubusercontent.com/22666460/41490465-ce2f5ec8-7111-11e8-8471-0116a35624aa.png)

**Comment by snehasi** [comment]
On investigating the issue further, I found out that this error happens when there is no description provided in the corresponding github issue.

**Comment by snehasi** [comment]
Hey @andyl I've tried fixing some bugs in the intern exercise, and am trying to test my changes locally. I'm getting an error : `bundler: failed to load command: rackup`, although the gems in gemfile  being referenced in `test_bench/exercise/intern/webapp/run ` have been installed.
Any idea why I am getting this error?

**Comment by snehasi** [comment]
The above errors were fixed and I've built the intern app locally.
Here's my PR on this error:  https://github.com/bugmark/test_bench/pull/111

**Comment by andyl** [comment]
Thanks for this - will look after the holiday...

**Comment by andyl** [comment]
Fixed - Sneha thank you for reporting AND fixing.  :-)
